 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author abhis
 */
public class HomepageCustomer extends javax.swing.JFrame {
    Subject sub = new Subject();
    Tracker tra = new Tracker(sub);
    /**
     * Creates new form HomepageCustomer
     */
    public HomepageCustomer() throws IOException {
        initComponents();
    }
    public String email_id;
    public HomepageCustomer(String email) throws IOException {
        initComponents();
        email_id = email;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_homepage_customer = new javax.swing.JLabel();
        btn_place_order = new javax.swing.JButton();
        btn_signout = new javax.swing.JButton();
        btn_change_password = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_homepage_customer.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lbl_homepage_customer.setText(" HomePage");

        btn_place_order.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_place_order.setText("Place Order");
        btn_place_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_place_orderActionPerformed(evt);
            }
        });

        btn_signout.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_signout.setText("Signout");
        btn_signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signoutActionPerformed(evt);
            }
        });

        btn_change_password.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btn_change_password.setText("Change Password");
        btn_change_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_change_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(699, 699, 699)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_signout, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_change_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_homepage_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_place_order, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1021, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lbl_homepage_customer)
                .addGap(110, 110, 110)
                .addComponent(btn_place_order)
                .addGap(35, 35, 35)
                .addComponent(btn_change_password)
                .addGap(32, 32, 32)
                .addComponent(btn_signout)
                .addContainerGap(692, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Customer Signout
    private void btn_signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signoutActionPerformed
        try {
            // TODO add your handling code here:\
            sub.signoutOutcome(email_id,1);
            new Login_Page().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(HomepageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_signoutActionPerformed

    private void btn_change_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_change_passwordActionPerformed
        try {
            // TODO add your handling code here:
            new Change_Password(email_id).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(HomepageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_change_passwordActionPerformed

    // Place Order page initiated for the Customer
    private void btn_place_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_place_orderActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try {
            new PlaceOrder(email_id).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(HomepageCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_place_orderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomepageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomepageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomepageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomepageCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    CafeManagementSystem.trackerOutput();
                    new HomepageCustomer().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(HomepageCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_change_password;
    private javax.swing.JButton btn_place_order;
    private javax.swing.JButton btn_signout;
    private javax.swing.JLabel lbl_homepage_customer;
    // End of variables declaration//GEN-END:variables
}
