/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import basic_models.Bill;
import basic_models.Categories;
import basic_models.SubCategories;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import pdf.pdfOpen;
import data_access_objects.BillDataAccessObject;
import data_access_objects.CategoriesDataAccessObject;
import data_access_objects.SubCategoriesDataAccessObject;
import static data_access_objects.SubCategoriesDataAccessObject.filterSubCategoryByName;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Acer
 */
public class PlaceOrder extends javax.swing.JFrame {
    Subject sub = new Subject();
    Tracker tra = new Tracker(sub);
    public int billId = 1;
    public int finalTotal = 0;
    public int subcategoryPrice = 0;
    public int subcategoryTotal = 0;
    public String email_pattern = "^[\\w._%+-]+@[\\w.-]+.[a-zA-Z]{2,}$";
    public String mobile_pattern = "^[0-9]{10}$";
    public String customerEmail; 

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() throws IOException {
        initComponents();
    }
    
    public PlaceOrder(String email) throws IOException {
        initComponents();
        txt_subcategory_name.setEditable(false);
        txt_subcategory_price.setEditable(false);
        txt_subcategory_total.setEditable(false);
        btn_add_to_cart.setEnabled(false);
        btn_generate_bill.setEnabled(false);
        JFormattedTextField t = ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
        t.setEnabled(false);
        customerEmail = email;
    }
    
    public void subcategoryNameByCategory(String category){
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0);
        ArrayList<SubCategories> list = SubCategoriesDataAccessObject.getAllRecordsByCategory(category);
        Iterator<SubCategories> itr = list.iterator();
        while(itr.hasNext()){
            SubCategories subcategories_obj = itr.next();
            dt.addRow(new Object[]{subcategories_obj.getName()});
        }
    }
    
    public void subcategoryNameByCategory(String name, String category){
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0);
        ArrayList<SubCategories> list = SubCategoriesDataAccessObject.filterSubCategoryByName(name, category);
        Iterator<SubCategories> itr = list.iterator();
        while(itr.hasNext()){
            SubCategories subcategories_obj = itr.next();
            dt.addRow(new Object[]{subcategories_obj.getName()});
        }
    }
    
    public void clearSubCategoryFields(){
        txt_subcategory_name.setText("");
        txt_subcategory_price.setText("");
        jSpinner1.setValue(1);
        txt_subcategory_total.setText("");
        btn_add_to_cart.setEnabled(false);
    }
    
    public void validateFields(){
        String customerName = txt_cust_name.getText();
        String customerMobileNumber = txt_cust_mobile_number.getText();
        String customerEmail = txt_cust_email.getText();
        if(!customerName.equals("") && customerMobileNumber.matches(mobile_pattern) && customerMobileNumber.length() == 10 && customerEmail.matches(email_pattern) && finalTotal > 0){
            btn_generate_bill.setEnabled(true);
        }
        else{
            btn_generate_bill.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_cust_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cust_mobile_number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cust_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_subcategory_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_subcategory_price = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_subcategory_total = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_add_to_cart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbl_final_total = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_generate_bill = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Place Order");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Bill Id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer Details");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Name");

        txt_cust_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cust_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cust_nameKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mobile Number");

        txt_cust_mobile_number.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cust_mobile_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cust_mobile_numberKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email");

        txt_cust_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cust_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cust_emailKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Category");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Name");

        txt_subcategory_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Price");

        txt_subcategory_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Quantity");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Total");

        txt_subcategory_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_add_to_cart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_add_to_cart.setText("Add to Cart");
        btn_add_to_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_to_cartActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        lbl_final_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_final_total.setText("Final Total:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("00");

        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_generate_bill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_generate_bill.setText("Generate Bill");
        btn_generate_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generate_billActionPerformed(evt);
            }
        });

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel13.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_cust_mobile_number)
                        .addComponent(txt_cust_name)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_cust_email)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_back))
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_final_total, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_generate_bill))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_add_to_cart))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_subcategory_name, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_subcategory_price)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_subcategory_total, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(txt_cust_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cust_mobile_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(txt_cust_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_back))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_subcategory_price)
                            .addComponent(txt_subcategory_name))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_subcategory_total, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jSpinner1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear)
                            .addComponent(btn_add_to_cart)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_final_total, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_generate_bill))
                .addGap(296, 296, 296))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        try {
            // TODO add your handling code here:
            setVisible(false);
            new HomepageCustomer(customerEmail).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_generate_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generate_billActionPerformed
        // TODO add your handling code here:
        String customerName = txt_cust_name.getText();
        String customerMobileNumber = txt_cust_mobile_number.getText();
        String createdBy = txt_cust_email.getText();
        SimpleDateFormat df = new SimpleDateFormat("MM-dd-yyyy");
        Date date = new Date();
        String dateToday = df.format(date);
        String total = String.valueOf(finalTotal);
        Bill bill = new Bill();
        bill.setId(billId);
        bill.setName(customerName);
        bill.setMobile_number(customerMobileNumber);
        bill.setEmail(customerEmail);
        bill.setDate(dateToday);
        bill.setTotal(total);
        bill.setCreatedBy(createdBy);
        BillDataAccessObject.saveValue(bill);
        
        // Code for creating a document of the bill
        String path = "D:\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + billId + ".pdf"));
            doc.open();
            Paragraph cafeName = new Paragraph("                                                                 Cafe Durga\n");
            doc.add(cafeName);
            Paragraph space = new Paragraph("***************************************************************************************************************\n");
            doc.add(space);
            Paragraph para3 = new Paragraph("\tBill ID: "+billId+"\nCustomer Name: "+customerName+"\nFinal Total: "+finalTotal);
            doc.add(para3);
            doc.add(space);
            PdfPTable t1 = new PdfPTable(4);
            t1.addCell("Name");
            t1.addCell("Price");
            t1.addCell("Quantity");
            t1.addCell("Total");
            for(int i=0; i<jTable2.getRowCount();i++){
                String x = jTable2.getValueAt(i,0).toString();
                String y = jTable2.getValueAt(i,1).toString();
                String z = jTable2.getValueAt(i,2).toString();
                String r = jTable2.getValueAt(i,3).toString();
                t1.addCell(x);
                t1.addCell(y);
                t1.addCell(z);
                t1.addCell(r);
            }
            doc.add(t1);
            doc.add(space);
            Paragraph ThxMsg = new Paragraph("Thank you for visiting our Cafe!");
            doc.add(ThxMsg);
            //open pdf for viewing
            pdfOpen.openById(String.valueOf(billId));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        try {
            sub.orderPlacedOutcome(customerEmail);
        } catch (IOException ex) {
            Logger.getLogger(Signup_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
        try {
            new PlaceOrder(customerEmail).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_generate_billActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId = Integer.parseInt(BillDataAccessObject.getId());
        jLabel13.setText(BillDataAccessObject.getId());
        ArrayList<Categories> list = CategoriesDataAccessObject.getAllRecords();
        Iterator<Categories> itr = list.iterator();
        while(itr.hasNext()){
            Categories categories_obj = itr.next();
            jComboBox1.addItem(categories_obj.getName());          
        }
        String categories = (String) jComboBox1.getSelectedItem();
        subcategoryNameByCategory(categories);
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String SubCategoryName = model.getValueAt(index, 0).toString();
        SubCategories subcategories = SubCategoriesDataAccessObject.getSubCategoryByName(SubCategoryName);
        txt_subcategory_name.setText(subcategories.getName());
        txt_subcategory_price.setText(subcategories.getPrice());
        jSpinner1.setValue(1);
        txt_subcategory_total.setText(subcategories.getPrice());
        subcategoryPrice = Integer.parseInt(subcategories.getPrice());
        subcategoryTotal = Integer.parseInt(subcategories.getPrice());
        btn_add_to_cart.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int quantity = (Integer) jSpinner1.getValue();
        if(quantity <= 1){
            jSpinner1.setValue(1);
            quantity = 1;
        }
        subcategoryTotal = subcategoryPrice * quantity;
        txt_subcategory_total.setText(String.valueOf(subcategoryTotal));
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String category = (String) jComboBox1.getSelectedItem();
        subcategoryNameByCategory(category);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_add_to_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_to_cartActionPerformed
        // TODO add your handling code here:
        String name = txt_subcategory_name.getText();
        String price = txt_subcategory_price.getText();
        String quantity = String.valueOf(jSpinner1.getValue());
        DefaultTableModel dt = (DefaultTableModel) jTable2.getModel();
        dt.addRow(new Object[]{name, price, quantity, subcategoryTotal});
        finalTotal = finalTotal + subcategoryTotal;
        jLabel14.setText(String.valueOf(finalTotal));
        
        clearSubCategoryFields();
        validateFields();
    }//GEN-LAST:event_btn_add_to_cartActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clearSubCategoryFields();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_cust_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cust_nameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txt_cust_nameKeyReleased

    private void txt_cust_mobile_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cust_mobile_numberKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txt_cust_mobile_numberKeyReleased

    private void txt_cust_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cust_emailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txt_cust_emailKeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int index = jTable2.getSelectedRow();
        int x = JOptionPane.showConfirmDialog(null,"Do you want to move the selected subcategory?","Select",JOptionPane.YES_NO_OPTION);
        if(x==0){
            TableModel model = jTable2.getModel();
            String total = model.getValueAt(index,3).toString();
            finalTotal = finalTotal - Integer.parseInt(total);
            jLabel14.setText(String.valueOf(finalTotal));
            ((DefaultTableModel) jTable2.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    CafeManagementSystem.trackerOutput();
                    new PlaceOrder().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_to_cart;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_generate_bill;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_final_total;
    private javax.swing.JTextField txt_cust_email;
    private javax.swing.JTextField txt_cust_mobile_number;
    private javax.swing.JTextField txt_cust_name;
    private javax.swing.JTextField txt_subcategory_name;
    private javax.swing.JTextField txt_subcategory_price;
    private javax.swing.JTextField txt_subcategory_total;
    // End of variables declaration//GEN-END:variables
}
